media:
  input: images
  output: images

content:
  - name: news
    label: News
    path: content/news
    type: collection
    filename: "{year}-{month}-{day}-{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: text

  - name: positions
    label: Open Positions
    path: content/positions
    type: collection
    filename: "{year}-{month}-{day}-{slug}.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Description
        type: text
