media:
  input: images
  output: images

content:

  - name: news
    label: News
    path: content/news
    type: collection
    filename: "{year}-{month}-{day}-{slug}.md"

    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: body
        type: text


  - name: positions
    label: Positions
    path: content/positions
    type: collection
    filename: "{year}-{month}-{day}-{slug}.md"

    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: body
        type: text
