backend:
  name: github
  repo: picnics-anr
  branch: main

media_folder: "images"
public_folder: "/images"

collections:

  - name: "news"
    label: "News"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }


  - name: "people"
    label: "People"
    folder: "content/people"
    create: true

    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown" }
